### PR TITLE
Added imgaug for advanced data augmentation

### PR DESCRIPTION
**Pull request by mathetes87**
Initial commit to add imgaug repo for advanced data augmentation. May need changes to ease usage

### CODE REVIEW

**Comment by mathetes87** [comment]
Also, the default parameters copied from the repo's website are way too aggressive. Before merging I can tweak them a little... just can't do it right now

**Comment by mathetes87** [comment]
Ok, now it should be ready to use. I kept the old data augmentation, but it is really easy to ditch it in favour of this one if you want

**Comment by yhenon** [comment]
Hi,
Thanks for this PR - it looks good. I'm still testing it since there are numerous changes. Only major change is to drop the `config.pickle` from the commit, it's not needed since it's autogenerated when running train_frcnn.

**Comment by mathetes87** [comment]
Ok, thanks! It should be good now, take the time needed though!

**Comment by mathetes87** [comment]
Do you need any further changes?

**Comment by yhenon** [comment]
No it looks good, I've been busy lately. I'll finish testing and merge it in the next 1-2 days.

**Comment by yhenon** [comment]
Sorry for the delay in reviewing this, it's been busy

**Comment by mathetes87** [comment]
@yhenon  no problem.

**Comment by mathetes87** [comment]
@yhenon if everything is Ok please merge the changes, so as to not have conflicts with further merges. Cheers

**Comment by mathetes87** [comment]
Closing this...

**Pull request closed without merging**
