### PR TITLE
Now compatible with windows and python 3.5

### PR DESCRIPTION
**Pull request by Ahleroy**
Compatibility with Python 3.5 on windows.

- Change xrange to range in data_generator.py
- Change iteritem to item in train_frcnn.py and test_frcnn.py
- Use floor division line 345 in data_generator.py
- Change import "file" to from . import "file"
- Rectified to drawing of the rectangle inside test_frcnn.py
- change data.next() to next(data) everywhere
- Change the open mode of the file from text to binary ('w' and 'r' to 'wb' and 'rb')

### CODE REVIEW

**Comment by yhenon** [comment]
This look great - thanks for the PR!
I have a bunch of changes I'm about to push, I'll be ready to merge this in a day or two.

**Comment by chairath** [comment]
thank you so much for helping me save time but I still found this "Exception: 'float' object cannot be interpreted as an integer" , do you know how to solve it?

**Comment by Ahleroy** [comment]
Indeed I found why.
I will change it this evening.

Regards,

**Comment by Ahleroy** [comment]
Corrected.

**Comment by chairath** [comment]
Thanks , it works

**Comment by alexattia** [comment]
Great work! Works on Mac and Python 3.5.3

**Comment by yhenon** [comment]
Merged with a few extra fixes - thank you @Ahleroy

**Pull request merged**
