### PR TITLE
vgg.py: floating point -> floor division in get_img_output_length

### PR DESCRIPTION
**Pull request by JonasHarnau**
Exchanged floating point for floor division to yield integer valued image dimensions. 
This had caused a freeze in `train_frcnn.py` for me through line 181 `next(data_gen_train)` coming through `get_anchor_gt(...)` and ultimately `calc_rpn(...)`.

### CODE REVIEW

**Comment by Abhijit-2592** [comment]
@JonasHarnau  By freezing you mean no output after it displays ?

> Started training
> epoch: 1/10000
> <No output afterwards>

**Comment by JonasHarnau** [comment]
@Abhijit-2592 yes exactly! The issue is that the float division (/) yields a float valued pixel value which unfortunately doesn't yield an error but simply freezes everything. Floor division (//)  fixes the issue. The Resnet implementation uses floor division and thus does not run into the problem.

**Comment by Abhijit-2592** [comment]
@JonasHarnau  Thanks man it is working! And the num 16 in 
`return input_length//16` is the rpn stride right?

**Comment by JonasHarnau** [comment]
Good to hear :)! 
From my understanding the ``get_img_output_length`` maps the input image size to the output size of the last shared convolutional layer. Here, that is ``block5_conv3``. In VGG16 the size reductions come solely from the Max-Pooling layers with stride 2 of which there are four. Thus the output of the shared layers is 1/2<sup>4</sup>= 1/16 the input size.

**Comment by Abhijit-2592** [comment]
@JonasHarnau  Thanks ! That makes perfect sense

**Comment by JonasHarnau** [comment]
@Abhijit-2592 yes, the 16 is random in as far as the network architecture is arbitrary. Keeping the architecture fixed, the total stride of the last shared conv. layer given the input image size is always 16.  My understanding from the quoted paragraph is that, since they resize the shorter side of the input image to 600, this translates to an 'effective' stride of 10 on the average PASCAL image (375/600 * 16 = 10). However, this would differ for each individual input image: if you use a smaller picture as input the effective stride would decrease, e.g. for a 200x150 image the 'effective' stride on the original image is 150/600 * 16 = 4. On the other hand, for a larger image the 'effective' stride goes up.

**Comment by Abhijit-2592** [comment]
@JonasHarnau  Thanks for your quick responce :) . Thanks for confirming it (was pretty vague until now :P). And I guess this code already deals with finding the effective stride (10 for pascal VOC) depending on the specified rpn_stride (default 16) and smaller side of input image before resizing (~375 for Pascal VOC). 

Thus we can easily add any arbitrary CNN trained on keras for image classification as a fixed feature extractor by the following the steps:
1)  strip the layers of the custom network until we get the required convolution layer.
2) And define get_img_output_length()  accordingly.

I am kinda trying to make this code into a small API (Inspired from the recent tensorflow's object detection API ) with this feature. So that almost any classification model trained on keras can be extended to an object detection network with minimal effort. Interested in joining?

**Comment by JonasHarnau** [comment]
@Abhijit-2592 apologies for the delay. That sounds cool, but I don't think I have the time for it right now. It would be great to have a look at it once you're done!

**Comment by yhenon** [comment]
Thanks for the PR - I made a change for python2/3 compatibility and I'm merging it

**Pull request merged**
